[[dnas]]
id = "game-dna"
file = "./dist/generic-game.dna.json"
hash = "QmUnxGv8p8PG71AWh88sNztxndyKK9WUiy94S29RU7jhg7"


[[agents]]
id = "agent1"
name = "agent1"
public_address = "HcScjcgKqXC5pmfvka9DmtEJwVr548yd86UPtJGGoue9ynuikuRTN7oE5zcjgbi"
keystore_file = "./agent1.keystore"

[[agents]]
id = "agent2"
name = "agent2"
public_address = "HcScidPSdAT43q9qirJwt5rHJYjjsvougV3jgSBwdJujszw3bBu5Mktr74Rgnea"
keystore_file = "./agent2.keystore"


[[instances]]
id = "instance1"
dna = "game-dna"
agent = "agent1"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[instances]]
id = "instance2"
dna = "game-dna"
agent = "agent2"
[instances.storage]
type = "memory"
path = "tmp-storage"


[[interfaces]]
id = "http-interface1"
[interfaces.driver]
type = "http"
port = 3000
[[interfaces.instances]]
id = "instance1"
[[interfaces.instances]]
id = "instance2"
